### PR TITLE
Added Bluemix support and simplified application.

### PR DESCRIPTION
**Pull request by craigkj312**
This PR adds all the necessary files to push the application to Bluemix. It also makes significant changes to main.swift by removing all the different code examples that can be put in docs and focusing only on serving static content, GET requests, and starting the server.

### CODE REVIEW

**Comment by ianpartridge** [comment]
I think we should split this into two PRs.  One for the Bluemix changes, and another for the simplification.

Personally, while the Bluemix support is important (and so is Heroku), I'm not sure we should be removing functionality from this application.  We should consider refactoring it so that visiting the default route provides Kitura education etc. and gives links to other routes that demo specific functionality.

**Comment by rolivieri** [comment]
@ianpartridge Here’s the context around this pull request. As part of our deliverables for the next month, the Kitura-Sample should be updated so it can be pushed/deployed to Bluemix using a CF buildpack. In addition to this, during the SCRUM earlier today, the team discussed the idea of simplifying the Kitura-Sample so that it showcases the main aspects of the Kitura framework as opposed to attempting to showcase every single aspect that Kitura supports (e.g. templating). We are thinking that separate examples could be used to showcase templating, redis, cloudant, etc. instead of having all of them bundled up under one single app. Kyle volunteered to help us with this and submitted this PR after making these changes. The templating sample code was removed in this PR. We have a separate repo that showcases how to use stencil: https://github.com/IBM-Swift/Kitura-SampleStencil.

**Comment by craigkj312** [comment]
It should also be noted that the templating was breaking breaking the Bluemix routes. Which is another reason I chose to remove it when adding Bluemix support.

Granted, I removed a lot more than just templating with this PR. I stripped the application down to showing essentially the bare minimum for a Kitura application that serves static content and has a basic REST interface.

I could make a separate PR that adds Bluemix support and only removes templating while keeping the rest of the examples in main.swift, but I feel that this overcomplicates the sample for a starting Kitura developer and that those examples should be shown in the Kitura docs.

Would you still prefer I do that? Then do the rest of the simplification in another PR.

**Comment by craigkj312** [comment]
That commit adds back in most of the examples. Notable examples that are still missing:
- Basic Auth Middleware
- Multiple Handler Blocks
- Custom "Not Found"
- Handling errors that get set

And of course:
- Templating

**Comment by ianpartridge** [comment]
> the Kitura-Sample should be updated so it can be pushed/deployed to Bluemix using a CF buildpack. 

Totally agree - this is really important.

> In addition to this, during the SCRUM earlier today, the team discussed the idea of simplifying the Kitura-Sample so that it showcases the main aspects of the Kitura framework as opposed to attempting to showcase every single aspect that Kitura supports (e.g. templating). We are thinking that separate examples could be used to showcase templating, redis, cloudant, etc. instead of having all of them bundled up under one single app.

I'm not so sure about this.  The Kitura-Sample app is already quite simple.  Rather than have lots more repos (making it harder to find information) I would prefer to structure the Kitura-Sample app so that the different pieces of functionality are easy to find.

For example, we could have separate routes to showcase templating, redis, cloudant etc. The code could be split into separate files.  The main file/route would link off to different sub-topics.

**Comment by dfirsht** [comment]
This PR has been moved to a new project: https://github.com/IBM-Swift/Kitura-Starter-Bluemix.

**Pull request closed without merging**
